### ISSUE TITLE
Debugger setup is crash looping

### ISSUE THREAD

**Issue by kosapo** [vadzappa/gomon-docker#4]
Seems that after some recent updates docker on Mac started to work slower and now the process is almost always being killed [here](https://github.com/vadzappa/gomon-docker/blob/master/check-alive.sh#L23) because $(pidof debug_bin) is empty

After that, it’s being restarted and killed again, so it's impossible to start a debugger.

This helped to resolve the problem locally, could not make a PR though due to lack of rights.

![Screenshot 2021-10-20 at 15 06 53](https://user-images.githubusercontent.com/22326561/138089713-7931bc46-e472-4cab-ba46-411a596a830f.png)

**Comment by vadzappa** [comment]
Actually, added you as collaborator :) now you can open PRs
